### ISSUE TITLE
Need to improve ux on mobile

### ISSUE THREAD

**Issue by alexzhang1030** [ChuYang-FE/tools-for-teachers#2]
When I open this preview page on my phone, the ux is very bad. So we need to improve it.

👇🏻 This is a picture
![image](https://user-images.githubusercontent.com/49969959/159933109-4ec2b5e5-c2c6-496c-af4b-34e77018e52e.png)

**Comment by ChuYang-FE** [comment]
Thank you for your suggestions. I'll enhance the ux on the mobile devices later~

**Comment by ChuYang-FE** [comment]
#

**Comment by ChuYang-FE** [comment]
Done~
